### ISSUE TITLE
View balance on Send Coins

### ISSUE THREAD

**Issue by themeadery** [laanwj/bitcoin-qt#24]
Sometimes I want to drain my wallet and I cannot see what my balance is when I am on the Send Coins tab.  This causes me to go back and forth to remember all 8 digits, however the amount clears out in that field if you navigate away so you have to remember it all in one shot.  You might say, "Why don't you just copy paste".  Well, I usually copy-paste the bitcoin address, so again it is impossible to go look at my balance after pasting because it will clear the field.

**Comment by laanwj** [comment]
Yes that sounds reasonable. It should probably show the current balance
somewhere on the sending tab, so you know how much you can send.

**Comment by jim618** [comment]
On the MultiBit screen, I ended up having to put both the 'estimated balance' (including pending receipts and bitcoin tied up in change' and the 'available to spend' balance i.e. the unencumbered transactions in your wallet.

Do you include the 0/unconfirmed in the total balance ?   If you do NOT, then it isn't a problem but if you do it is worth giving the user some feedback as to how much bitcoin is actually available to spend at that precise moment.

Jim

**Comment by laanwj** [comment]
In my client I have "Balance" and "Unconfirmed balance".
"Balance" includes only the confirmed transactions (and is the amount that
can actually be spent), whereas "Unconfirmed balance" includes the
transactions with 0 confirmations which are not sure yet

**Comment by jim618** [comment]
I think that is a better way round actually - I think I will copy that
terminology if you don't mind.   Makes it clearer that the 0/Unconfirmed
'is not there yet' for the average user.

Regards

Jim

On Tuesday, September 20, 2011 11:02 AM, "Wladimir J. van der Laan"
reply@reply.github.com
wrote:

> In my client I have "Balance" and "Unconfirmed balance".
> "Balance" includes only the confirmed transactions (and is the amount
> that
> can actually be spent), whereas "Unconfirmed balance" includes the
> transactions with 0 confirmations which are not sure yet
> 
> On Tue, Sep 20, 2011 at 6:11 PM, Jim Burton <

**Comment by Matoking** [comment]
I just did this. It currently looks like this: http://i.imgur.com/oluv2.png

I'll commit it very soon.

**Comment by laanwj** [comment]
looks good @matoking, I was also thinking of putting it close to the send
button
Op 21 sep. 2011 15:02 schreef "Matoking" <
reply@reply.github.com>
het volgende:

**Comment by Matoking** [comment]
Done.
https://github.com/Matoking/bitcoin-qt/commit/bae0e1671bcf6cc67b437123c81c8248ee3bfa0e

Now to bring my fork up-to-date. It was a nightmare previous time, hopefully this time it'll be easier.

EDIT :
Done. Feel free to add it to the master repository if you think it looks clean enough.

**Comment by laanwj** [comment]
Matoking: I'd connect the balancechanged signal from the model directly, instead of going through overviewpage, but apart from that the change is OK. 

Git-related comment: your commit is full of unrelated changes; it is easier for others if you keep commits as atomic (and related to one functional change) as possible. In that case I could simply do "git cherry-pick <commit>".

What problem do you get with keeping your fork up-to-date?

**Comment by Matoking** [comment]
When there are conflicts with multiple files it becomes annoying to fix them. I'd like Git to just ignore those and just replace the files completely. I still can't use Git pretty well, probably explains all those unrelated changes.

And yeah, I'll try implementing it using the model. Using the signal from Overview page I don't need to bother with unit conversions or anything, so it seemed the most straight-forward way of doing it.

**Comment by laanwj** [comment]
Seems you forgot to commit after the merge?

If it is messed up beyond repair you could always do "git reset --hard
remotes/origin/master" to completely get rid of all changes. This will get
rid of all local changes in all files, though, be careful...

There is also a flag to "git merge" to ignore the local versions and always
use the remote version on conflicts, but that is even more dangerous
generally :-)

**Comment by Matoking** [comment]
What, it should be up-to-date with the latest commit?

I'll probably just do a hard reset.

**Comment by laanwj** [comment]
Please wait with pushing after the reset until i've pulled your changes
though. Otherwise they are lost. I'll do this in the evening.
Op 22 sep. 2011 13:36 schreef "Matoking" <
reply@reply.github.com>
het volgende:

**Comment by Matoking** [comment]
Qt Creator didn't save everything the first time around, explaining my embarassing commits.

I think I should just get a GUI version of Git.

EDIT :
Ok, it should be ok now. If it's not, I'll just obliterate my Git repository from orbit and start over again.

**Comment by Matoking** [comment]
Good to see you got it fixed before me. I ended up doing what you suggested, thanks. 

I'll try not to cause more mess like that next time. :P
